name: Publish package
on:
  release:
    types:
      - prereleased
      - released

jobs:
  publishpackage:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v3
      name: Code checkout
      with:
        persist-credentials: true
        ref: main
        fetch-depth: 2
        submodules: true

    # Install basic tools
    - uses: actions/setup-node@v3
      name: Setup node.js
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/
    - run: sudo npm install -g ts-node typescript
      name: Install typescript and ts-node

    - name: Edit version
      shell: node {0}
      run: |
        const fs = require("fs");
        const path = require("path");
        const packagePath = path.join(process.cwd(), "package.json");
        const package = JSON.parse(fs.readFileSync(packagePath, "utf8"));
        package.version = "${{ github.ref }}";
        package.version = package.version.replace(/[A-Za-z_\/]+/, "");
        fs.writeFileSync(packagePath, JSON.stringify(package, null, 2));

    # Add version to environment variables
    - name: Add version to environment variables
      run: |
        cat package.json | jq -r '.version' > /tmp/version.txt
        echo "PACKAGE_VERSION=$(cat /tmp/version.txt)" >> $GITHUB_ENV

    # Install depencides and build
    - run: npm ci
    - run: npm run build

    # Create pull request to update version in main branch
    - uses: peter-evans/create-pull-request@v4
      name: Create Pull Request
      continue-on-error: true
      with:
        commit-message: Update version v${{ env.PACKAGE_VERSION }}
        delete-branch: true
        assignees: SirHerobrine23
        reviewers: SirHerobrine23
        branch: update-version
        title: Update package version v${{ env.PACKAGE_VERSION }}
        body: Auto update package version, created with GitHub Actions

    # Publish
    - run: npm publish --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}
      name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MPM_PUBLISH_TOKEN }}